#!/bin/sh

function error_quit {
	echo "Caught error, '$1' quitting" 1>&2
	exit 1
}

if [ $# -ne 1 ] ; then
	echo "Usage: $0 version-number" 1>&2
	exit 1
fi

vers=$1
tar=/homes/olson/p3-$vers.tgz

if [ ! -f $tar ] ; then
	echo "Tarfile $tar does not exist" 1>&2
	exit 1
fi

if [ ! -d scripts ] ; then
	echo "No scripts dir; is this not a repo?" 1>&2
	exit 1
fi

tar xzfp $tar
git rm -f -r  lib scripts 
mv p3-$vers/{lib,scripts} .
git add lib scripts
